-- Initial schema for the notes API.
-- Flyway applies this once and records it in its flyway_schema_history table,
-- so it will never run again. Future changes go in new V2__, V3__ ... files.

CREATE TABLE notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255)                NOT NULL,
    content    VARCHAR(10000)              NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- Element-collection table for tags (matches @CollectionTable on the Note entity).
-- ON DELETE CASCADE removes a note's tags when the note is deleted.
CREATE TABLE note_tags (
    note_id BIGINT      NOT NULL REFERENCES notes (id) ON DELETE CASCADE,
    tag     VARCHAR(50)
);

CREATE INDEX idx_note_tags_note_id ON note_tags (note_id);
